# Generated by Django 5.0.7 on 2024-08-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pubication', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('pub_text', models.TextField(max_length=255, verbose_name='publications')),
                ('pub_title', models.CharField(max_length=200, verbose_name='publication title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='publication')),
            ],
            options={
                'db_table': 'publications',
            },
        ),
    ]
